name: invest_cryptocurrency
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  flutter_svg: 2.0.10
  flutter_bloc: 8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.0
  build_runner: 2.4.13
  freezed: 2.5.7
  json_serializable: 6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_intl:
  enabled: true
